# docker-compose.yml
services:

  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: atalaia-app
    container_name: atalaia-app
    restart: unless-stopped
    tty: true
    dns:
    - 8.8.8.8
    - 1.1.1.1
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - atalaia-network

  # Nginx Service
  web:
    image: nginx:alpine
    container_name: atalaia-web
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443" # Porta 8443 no host mapeada para 443 no container
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./.docker/nginx/ssl:/etc/nginx/ssl # Pasta para os certificados
    networks:
      - atalaia-network

  # Database Service (MySQL 5.7 para compatibilidade)
  db:
    image: mysql:5.7
    container_name: atalaia-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
    networks:
      - atalaia-network

networks:
  atalaia-network:
    driver: bridge